# Generated by Django 2.1.3 on 2018-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_auth', '0002_auto_20181126_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.FloatField(default=1, null=True),
        ),
    ]
