# Generated by Django 2.1.3 on 2018-11-28 10:13

import builder_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder_auth', '0003_auto_20181126_1957'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', builder_auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
