# Generated by Django 2.1.3 on 2018-12-15 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_planfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='answer_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of getting receiver answer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 20, 13, 41, 837920, tzinfo=utc), verbose_name='Date of setting sender request'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='files/loads/%Y/%m/%d'),
        ),
    ]
