# Generated by Django 2.1.3 on 2018-12-01 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_auto_20181201_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
